name: 'fintech_data_platform'
version: '1.0.0'
config-version: 2

profile: 'fintech_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fintech_data_platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
    core:
      +materialized: table

vars:
  # Variables for the project
  transaction_table: "transactions"
  fraud_alert_table: "fraud_alerts"
  
  # Data quality thresholds
  max_risk_score: 1.0
  min_transaction_amount: 0.01
  max_transaction_amount: 1000000.0

seeds:
  fintech_data_platform:
    +column_types:
      transaction_id: varchar(255)
      amount: decimal(10,2)
      risk_score: decimal(3,2)

tests:
  +store_failures: true
  +warn_if: ">100"
  +error_if: ">1000"
