global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application
  - job_name: 'fintech-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Dashboard application
  - job_name: 'fintech-dashboard'
    static_configs:
      - targets: ['dashboard:8061']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Kafka metrics (if using JMX exporter)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9404']
    scrape_interval: 30s

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s
